import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Snif Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      
    <html lang='en'>
    <body>
        
    <div className='main' >
        <div  className='gradient' />
    </div>
    <main className='app'>
        {children}
    </main>
    
    </body>
</html>
  

  )
}
